[functions]
directory = "_functions"

[[redirects]]
from = "/screenshot/*"
to = "/.netlify/functions/screenshot"
status = 200
force = true

[context.production.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"